### ISSUE TITLE
Does not work in Matrix.

### ISSUE THREAD

**Issue by rikardfries** [dodoadoodoo/kodi-sverigesradio#3]
Does not work in Matrix since it is not Python 3.

**Comment by dodoadoodoo** [comment]
Do you have a log file?

**Comment by rikardfries** [comment]
Since it is depending on python 2 and Matrix is python 3 it is disabled and will not start.
So there is no log.

**Comment by dodoadoodoo** [comment]
Right, thanks for reporting. Will be fixed when time permits.

**Comment by dodoadoodoo** [comment]
Note to self: Check if new imports resolves this. 
```
<import addon="xbmc.python" version="3.0.0" />
<import addon="script.module.xbmcswift2" version="19.0.1"/>
<import addon="script.module.requests" version="2.22.0"/>
```

**Comment by dodoadoodoo** [comment]
Unfortunately, there seems to be some problem with urllib3. 
```
2021-05-24 20:18:38.742 T:15036   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'queue'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Daniel\AppData\Roaming\Kodi\addons\plugin.audio.sverigesradio\addon.py", line 8, in <module>
                                                       import requests
                                                     File "C:\Users\Daniel\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\__init__.py", line 43, in <module>
                                                       import urllib3
                                                     File "C:\Users\Daniel\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\__init__.py", line 13, in <module>
                                                       from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
                                                     File "C:\Users\Daniel\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 37, in <module>
                                                       from .packages.six.moves import queue
                                                     File "C:\Users\Daniel\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\packages\six.py", line 96, in __get__
                                                       result = self._resolve()
                                                     File "C:\Users\Daniel\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\packages\six.py", line 118, in _resolve
                                                       return _import_module(self.mod)
                                                     File "C:\Users\Daniel\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\packages\six.py", line 87, in _import_module
                                                       __import__(name)
                                                   ModuleNotFoundError: No module named 'queue'
                                                   -->End of Python script error report<--

```

Urllib3 is a dependency from requests. I'm not sure how to proceed here. Need to have a think, given my history I may be back in six months. (Personally, I'm still_ on Leia)
Update: This is possibly an Windows issue. If anyone is able to test on an OS that differentiates between lower and upper case I'd be grateful

**Comment by EvTheFuture** [comment]
It works for me on CoreElec 19 on an Odroid N2

**Comment by dodoadoodoo** [comment]
> It works for me on CoreElec 19 on an Odroid N2

As I suspected... 

Right, I'll try to get it submitted to the offical repo.
